project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - notebook/pages/*.qmd

website:
  title: "SPI-M-O"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo
    toc: true

execute:
  freeze: true
