---
title: "Comment on the end of the COVID-19 Inquiry"
---

*Reposting from a comment on a blog*

I think the Inquiry actively inhibited scientific evaluation of the work we produced during COVID-19.

I'm coming purely from an academic modeller's perspective, having spent the last few years gently asking around about who might be interested in evaluating the work of SPI-M.
The response has mostly been "we have to wait for the Inquiry".

I think there are a few reasons contributing to this, and frustratingly I still don't see a natural avenue for this work.
TLDR; I think burn-out, and academic (dis)incentives, have created a "missing middle" in the academic hierarchy where we might otherwise expect this work to come from.

As far as I can tell, up until now we've had:

(1) a catastrophic, wildfire level of burn-out among those contributing to the COVID response.
    We've discussed in some depth elsewhere (see: Wellcome Open Research paper)

(2) relatedly, rapid turnover among those who worked on the response - encouraged by the prevalence of short-term contracts in academia

(3) no professional incentives for retrospective evaluation work (i.e. difficult to get quick tractable publications out of evaluation, again a particular issue for those on more junior/short-term contracts)

(4) the Inquiry providing an active disincentive, by (a) quickly and thoroughly using up any of the very limited capacity that we had to reflect on COVID work; (b) providing a diversion for any attempt at reflection, towards a bureaucratic/legalistic/public office framing

I think this has meant we have had neither emotional nor professional capacity for serious, systematic evaluation of COVID-19 work.
And that makes it wildly frustrating that the Inquiry did not use whatever capacity we had, well.

Now the Inquiry is over I am still struggling to see where any scientific evaluation can come from, because of the biased losses to institutional memory:

(5) Among those in academia who worked on the real-time COVID response - we still have no capacity for retrospective evaluation, because we've spent the last 3-6 years seeking funding for entirely new work.
    (At best, this newly funded work might include some element of COVID-19 evaluation for background/learning from.)
    We also represent 'survivor bias': I think we've seen clear differential attrition among academic careers of responders

(6) Those in academia who might have capacity, tend to be junior researchers - who are unlikely to have directly worked on the response.
    This would make it very difficult to build a strategy for evaluating across the pandemic work as a whole, not to mention intimidating from the perspective of critiquing the work of one's (new) colleagues in a small field

I am personally very invested in attempting some meaningful evaluation of the modelling work that went into the COVID-19 response in the UK.
But it's taken... four or five years to get comfortable with even writing that up into a research proposal (and I am still missing all my deadlines).
