# LSHTM

**Brief evaluation: Exercise Pegasus at LSHTM / CMMID**[^1]\
2 December 2025 \| Kath Sherratt and participants in Exercise Pegasus at LSHTM

**Activity**.
Preparing for the exercise included senior staff disseminating information informally, then sharing with the "Outbreak response" CMMID theme.
16 staff/PhD researchers joined a dedicated Slack channel, with \~six actively contributing.
We held an initial planning meeting, to share interest and capacity, and agreed to use the exercise for testing existing methods while strongly discouraging out-of-hours work.
Subsequent communication and data sharing occurred via Slack and OneDrive.
The response work included early epidemiological parameter estimates, reviewing SPI-M-O requests to estimate resources needed to respond, and collaborative discussion of policy options during the "mitigation" phase.

**Strengths**

- Senior staff anticipated and shared the timing of SPI-M requests, drawing on experience from COVID-19\
- The outbreak response theme was a useful network for mobilising interested staff\
- General support from senior staff for managing response within working hours\
- Resources: Slack was essential for internal coordination of interest/capacity, institutional OneDrive useful for secure data sharing

**Weaknesses**

- "Trickle down" communication from SPI-M-O via senior staff, with information shared ad hoc in a mix of private and public Slack channels within CMMID, creating delays / uneven access, confusion, and ambiguous expectations.\
- Lack of ability to triage the volume of SPI-M-O requests, based on work being done elsewhere or SPI-M-O priorities, led to disengagement\
- Turnover since COVID-19 response meant many junior/mid-level researchers were unfamiliar with the SPI-M-O structure or expectations\
- LSHTM has no formal structure for managing outbreak response work alongside/instead of research.
  Competing commitments limited participation even among those interested and willing

**Lessons identified**

- CMMID lacked a structure for handling comms, work allocation, and data sharing, with a tension between the flexibility of informal channels vs possibly more efficient distribution with more structure.
  Use of OneDrive was secure, but using the CMMID Github organisation would allow wider access / code sharing.\
- LSHTM lacks a clear institutional mechanism for staff redeployment.
  The removal of institutional underwriting is a specific concern.
  Exercise Pegasus usefully prompted action within LSHTM to advocate for an institutional structure for triaging and supporting emergency outbreak response work.\
- Generally poor motivation to work on a simulation exercise.
  It would be helpful to set out the importance of exercises for preparation, with clearer incentives for participating, e.g. shareable / public outcomes.

# HPRU review

Presentation on Pegasus @ HPRU Away day

### Context

- *Format - 10 min presentation; structure based on an "after action review"*\
- *Aim - give context of Pegasus (incl.
  for those who didn't participate); prompt reflection/consensus on specific role of HPRU; provoke action to fulfil that role*\
- *Avoid - evaluating specific work during Pegasus / discussion of general UK pandemic response*

### Content

1. **What was supposed to happen?** (2-3 mins)\

- UK academia\
  - Reminder of UK emergency response information flow (COBR/SAGE/SPI-M structure)\
  - inquiry recommendations for pandemic simulation every 3 years & aims of Pegasus process as I understand it\
- HPRU *(from description on website)*\
  - Research-mode: "*enhances the ability of the UK Health Security Agency (UKHSA)... focus on collaboration and knowledge sharing... play a pivotal role in maintaining and growing UKHSA's scientific expertise"*\
    - operationalised as ?
      supporting UKHSA with implication UKHSA is the primary responder, focus on collaboration, training?\
  - Response-mode: "*deliver responsive research to tackle emerging or potential public health emergencies"*\
    - operationalised as small % staff time funded

2. **What actually happened?** (2-3 mins)\

- UK academia\
  - Brief description - actual information flow, requests, timing, feedback\
  - notes at[LSHTM Pegasus response](https://docs.google.com/document/d/1PVhXuzKmEeca6kLQHfkjXZ13qWIEuvovwOoypqSztOA/edit?tab=t.0)\
- HPRU\
  - check in / check feedback from HPRU funded RD/staff on role/time\
  - Brief notes from chat with Jon Mellor for UKHSA perspective (but confidential & keep specific to HPRU)

3. **What should we do differently next time?** (3-6 mins)\

- UK academia\
  - Be clear about conflicts & weaknesses in spi-m.[LSHTM Pegasus response](https://docs.google.com/document/d/1PVhXuzKmEeca6kLQHfkjXZ13qWIEuvovwOoypqSztOA/edit?tab=t.h47k0xiu3nxv#heading=h.4ekinkcm31nl)- thoughts re differentiation from UKHSA\
  - Both LSHTM and Imperial are now attempting to establish an institutional response policy\
- HPRU\
- Link back to specific aim of HPRU - explicitly aiming to support UKHSA - so should be expected to play greater role than academia in general\
- HPRU window is 5 years: what do we want to see in the next simulation in 3 years time?\
- What could we start doing now to prepare for that?
  What might we stop doing, or carry on as is?

# Brief piece

Context

- Context: Post-COVID capacity for emergency response\
- Academic capacity\
- HPRU established with ?20% capacity for response work\
- Pandemic simulations\
- Previous simulations: cygnet\
- The COVID Inquiry recommendations mandated a whole-of-government pandemic simulation exercise every three years (i.e. within each window of central government)\
- Pegasus the first of these
- In 9 years?
  In 24 years time?

[^1]: London School of Hygiene & Tropical Medicine; Centre for Mathematical Modelling of Infectious Disease
