# Commentary

## Book proposal

### Why a book?

- Giving a fair account of how and why SPI-M worked during COVID-19 requires an understanding of the historical development of SPI-M, its participants, and its role within the Westminster system
- There is a natural narrative arc in the successive generations of emergency response that SPI-M has grown out of
- The readership should be wider than academic modelling community; there are lessons here for any kind of expert advice in policy, scientific culture and consensus making under pressure, the use of science as a political tool and the resulting conflicts facing scientists.

### Audience

- Evidence consumers (public health, humanitarian aid, ...) seeking expert advice.
  - Why?
    This audience, at least in public health, seems to view SPI-M as a best practice to follow, but without clarity on how SPI-M really functions.
  - So what?
    The book should help them reflect on what they want, from who, in an emergency (not "more numbers better"), and provide (implicit) examples of better/worse options for executing this (e.g. group structure, conflict, elicitation).
- Academics looking to have policy impact.
  - Why?
    SPI-M in COVID-19 was an immediate and shocking collison between the worlds of academia and national politics
  - So what?
    This is an excellent example of the costs of policy facing work, and a good way to explore the responsibilities and boundaries of academics providing evidence with highly consequential use
- General public
  - Why?
    SPI-M is a matter of national interest - as a body with strong influence on the politicians and policies governing a democratic society, potentially at any time and with extreme and universal impact.

### Informative comparisons

- Hacking, The Taming of Chance
- Porter, Trust in Numbers
- Thompson, Escape from Model Land
- Schneider, Science as a Contact Sport
- Parkhurt, The Politics of Evidence

## History of SPI-M

Context: epidemiological analysis contributing to policy

Choice of approach

- Outbreak-by-outbreak\
- Outbreak phase: detection, wave, stand-down\
- Evaluation criteria: credibility/scientific validity, relevance/policy interaction, legitimacy/public accountability

Methods

- Survey - cohorts of analysts identified across outbreaks\
- Interviews - key informants (consistent participants), + ?large random selection of one-off participants\
- text mining & processing - e.g. relative term frequency across witness statements; topic modelling to identify role of quantitative work/reliance on modellers as experts; sentiment analysis; network analysis of co-mentions of people, institutions, topics

Themes:

- Resources - "we had a single computer"\
- Teams: who was working on what, when, where?
  What training did they have?
  Who left & where did they move to?
  Who stayed & why?\
  - Hypothesis - survivor bias & Matthew effect of self-reinforcing career path dependency\
  - Lessons: selection, recruitment, diversity, participation
